name: cd

on:
  workflow_run:
    workflows: ["ci"]   # Name of your CI workflow
    types:
      - completed       # Trigger when CI completes

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # only deploy if CI passed
    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull shivaaws69/netflix:latest
            docker stop py-app || true
            docker rm py-app || true
            docker run -d --name py-app -p 5000:5000 shivaaws69/netflix:latest

