name: cd

on:
  workflow_run:
    workflows: ["ci"]   # Name of your CI workflow
    types:
      - completed       # Trigger after CI completes

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Only deploy if CI passed
    steps:
      - name: Set Commit SHA
        run: echo "SHORT_SHA=${{ github.event.workflow_run.head_commit.id::7 }}" >> $GITHUB_ENV

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying commit $SHORT_SHA"
            docker pull shivaaws69/netflix:$SHORT_SHA
            docker stop py-app || true
            docker rm py-app || true
            docker run -d --name netflix -p 80:80 shivaaws69/netflix:$SHORT_SHA
